### ISSUE TITLE
piping data from another command to vibrant cli

### ISSUE THREAD

**Issue by lmj0011** [generaltso/vibrant#1]
Is it possible to feed an image to the vibrant cli tool from a unix pipe?

ie.

```sh
~$ curl https://i.imgur.com/nzcJuDx.png  | vibrant -json 
usage: vibrant [options] file

options:
  -compress
    	Strip whitespace from output.
  -css
    	Output results in CSS.
  -json
    	Output results in JSON.
  -lowercase
    	Use lowercase only for all output. (default true)
  -rgb
    	Output RGB instead of HTML hex, e.g. #ffffff.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 16 30609   16  4910    0     0  18374      0  0:00:01 --:--:--  0:00:01 18389
curl: (23) Failed writing body (1945 != 2759)
``` 

this does not work ^

I can achieve what I want though by saving to a temp file

eg.

```sh
~$ curl https://i.imgur.com/nzcJuDx.png  -o temp && vibrant -json temp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30609  100 30609    0     0   100k      0 --:--:-- --:--:-- --:--:--  100k
{
  "darkvibrant": {
    "color": "#004285",
    "text": "#ffffff"
  },
  "lightvibrant": {
    "color": "#7bbdff",
    "text": "#000000"
  },
  "vibrant": {
    "color": "#3f9fff",
    "text": "#ffffff"
  }
}
```

**Comment by dayvonjersen** [comment]
Hm, I could definitely explore adding a feature like this (i.e. read image data from stdin) to the reference implementation cli tool.

Do you have any other suggested improvements in mind after using it? e.g. the flags, default behavior, output, etc...

Thanks,
-tso

**Comment by lmj0011** [comment]
My plan is to wrap this library with a node.js server.

Basically you'll send the server an URL of an image, vibrant does its thing, and you get back the  json output of the color palette.

Having vibrant read directly from standard out would save a tiny bit of time in the process

**Comment by dayvonjersen** [comment]
@lmj0011 neat! 

I added reading stdin as a command-line flag `-i`:

```
$ vibrant image.jpg
     Vibrant: #ede01b, population: 1350
LightVibrant: #f5ae82, population: 2981
 DarkVibrant: #9d5f09, population: 438
       Muted: #5f8ca3, population: 2454
  LightMuted: #d6e2ec, population: 2933
   DarkMuted: #253948, population: 2529
$ cat image.jpg | vibrant -i
     Vibrant: #ede01b, population: 1350
LightVibrant: #f5ae82, population: 2981
 DarkVibrant: #9d5f09, population: 438
       Muted: #5f8ca3, population: 2454
  LightMuted: #d6e2ec, population: 2933
   DarkMuted: #253948, population: 2529
```

Automatically detecting whether there is data to read with stdin is a bit tricky/buggy on windows at least (you have to use `os.Stdin.Stat()` which then doesn't let you `Read()` idk probably a windows bug)

So I hope the `-i` isn't too inconvenient and I hope that my little tool fits well into your stack (at least well enough to let you ignore [node-vibrant](https://github.com/akfish/node-vibrant) >_>)

Happy hacking,
-tso

**Comment by lmj0011** [comment]
Thanks, been looking for a reason to start using go-lang anyway

**Comment by dayvonjersen** [comment]
@lmj0011 I hope that wasn't sarcasm, I added the feature ._.

**Comment by lmj0011** [comment]
It wasn't

**Comment by dayvonjersen** [comment]
Oh. My bad, sorry.

Enjoy your time using Go! It's a great language and useful for so many things! :D
